---08日志清理
USE [master]
GO
ALTER DATABASE liveBPDB_2013_04_19 SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE liveBPDB_2013_04_19 SET RECOVERY SIMPLE --简单模式
GO
USE liveBPDB_2013_04_19
GO
DBCC SHRINKFILE (N'iProcessDB_Log' , 11, TRUNCATEONLY)
GO

-------查询日志逻辑文件名
USE liveBPDB_2013_04_19
GO
SELECT file_id, name FROM sys.database_files
GO

---
USE [master]
GO
ALTER DATABASE liveBPDB_2013_04_19 SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE liveBPDB_2013_04_19 SET RECOVERY FULL --还原为完全模式
GO

方法二
--清空日志
DUMP TRANSACTION testdb WITH NO_LOG 
-截断事务日志 
BACKUP LOG testdb WITH NO_LOG
-收缩数据库 
DBCC SHRINKDATABASE(testdb)  WITH NO_INFOMSGS
